### ISSUE TITLE
can't import cadquery

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/fusion_neutronics_workflow#42]
How to reproduce the issue:

1) Run:

```
docker run -it -v ${PWD}:/home/fusion-neutronics-workflow/examples ghcr.io/fusion-energy/fusion-neutronics-workflow
```

using the latest tag

2) `cd examples`

3) `python`

4) execute: `import cadquery`

This produces:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cadquery/__init__.py", line 14, in <module>
    from .occ_impl import exporters
  File "/opt/conda/lib/python3.8/site-packages/cadquery/occ_impl/exporters/__init__.py", line 10, in <module>
    from ...cq import Workplane
  File "/opt/conda/lib/python3.8/site-packages/cadquery/cq.py", line 54, in <module>
    from .selectors import (
  File "/opt/conda/lib/python3.8/site-packages/cadquery/selectors.py", line 23, in <module>
    from pyparsing import (
ImportError: cannot import name 'upcaseTokens' from 'pyparsing' (/opt/conda/lib/python3.8/site-packages/pyparsing/__init__.py)
```

**Comment by RemDelaporteMathurin** [comment]
Subsenquently, I can't import paramak either

**Comment by RemDelaporteMathurin** [comment]
I don't think so cause I can also reproduce the error without importing paramak:

1) docker run -it --rm ghcr.io/fusion-energy/fusion-neutronics-workflow
2) run `python`
3) run `import cadquery`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cadquery/__init__.py", line 14, in <module>
    from .occ_impl import exporters
  File "/opt/conda/lib/python3.8/site-packages/cadquery/occ_impl/exporters/__init__.py", line 10, in <module>
    from ...cq import Workplane
  File "/opt/conda/lib/python3.8/site-packages/cadquery/cq.py", line 54, in <module>
    from .selectors import (
  File "/opt/conda/lib/python3.8/site-packages/cadquery/selectors.py", line 23, in <module>
    from pyparsing import (
ImportError: cannot import name 'upcaseTokens' from 'pyparsing' (/opt/conda/lib/python3.8/site-packages/pyparsing/__init__.py)
```

**Comment by RemDelaporteMathurin** [comment]
> This bug is due to the dockerfile installing paramak version 0.7 instead of the newer versions such as 0.8.1

Updating to paramak 0.8.1 didn't fix it apparently

https://github.com/fusion-energy/fusion_neutronics_workflow/runs/6653637317?check_suite_focus=true

**Comment by shimwell** [comment]
I think the latest release has fixed this error, both CI test routines are working again. Please reopen if this problem persists
